GET http://localhost/super-admin/test

###
GET http://localhost/user/test

###  add super admin
POST http://localhost/user/register
Content-Type: application/json

{
"name":"admin",
"email":"admin",
"password":"admin"
}


### Registration
POST http://localhost/user/register
Content-Type: application/json

{
"name":"laxman",
"email":"lakshman5296@gmail.com",
"password":"Laxmana@123"
}

### Login
POST http://localhost/user/login
Content-Type: application/json

{
"email":"admin",
"password":"admin"
}

### Assign role

PUT http://localhost/super-admin/role/user/lakshmana5296@gmail.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3VwZXJfYWRtaW4iLCJpYXQiOjE2Nzg0NzY3MDZ9.Z9syt_flo9Meh5jg2YVBnReW7rYbfUeKh2mYPZpMUx4

{
    "role":"admin"
}

### Get all users to whom role is not yet allocated
GET http://localhost/super-admin/role/not-assigned-users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3VwZXJfYWRtaW4iLCJpYXQiOjE2Nzg0NzY3MDZ9.Z9syt_flo9Meh5jg2YVBnReW7rYbfUeKh2mYPZpMUx4